<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" name="Test" tests="6" failures="1" timestamp="15 May 2020 02:26:48 GMT" time="0.126" errors="0">
  <testcase name="a" time="0.035" classname="com.org.mypac.TestNgClass"/>
  <testcase name="f" time="0.001" classname="com.org.mypac.TestNgClass"/>
  <testcase name="z" time="0.006" classname="com.org.mypac.TestNgClass">
    <skipped/>
  </testcase> <!-- z -->
  <testcase name="z" time="0.001" classname="com.org.mypac.TestNgClass">
    <skipped/>
  </testcase> <!-- z -->
  <testcase name="z" time="0.001" classname="com.org.mypac.TestNgClass">
    <skipped/>
  </testcase> <!-- z -->
  <testcase name="z" time="0.003" classname="com.org.mypac.TestNgClass">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;30&amp;gt; but was:&amp;lt;40&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<30> but was:<40>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at com.org.mypac.TestNgClass.z(TestNgClass.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- z -->
</testsuite> <!-- Test -->
